export const API = {
  BASE_URL: 'https://api.foursquare.com/v2/venues/search',
  CLIENT_ID: 'SJ0B5ZB5K4I3TLSOZFVKWEVV2DBBVWRWEC5JVLJ2JJUYR2NV',
  CLIENT_SECRET: '20YGPYOUYP0QPHNVHGIVIARHSTY1MFPQYOWCXPNDBOE5EPLT',
  V: '20120609'
};
